// Copyright 2025 International Digital Economy Academy
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

///|
/// Ported from `cosmic-text/src/buffer.rs` (cosmic-text is dual-licensed MIT OR Apache-2.0).
pub struct Metrics {
  /// Font size in pixels
  font_size : Float
  /// Line height in pixels
  line_height : Float
}

///|
pub fn Metrics::new(font_size : Float, line_height : Float) -> Metrics {
  Metrics::{ font_size, line_height }
}

///|
/// Create metrics with given font size and calculate line height using relative scale.
pub fn Metrics::relative(
  font_size : Float,
  line_height_scale : Float,
) -> Metrics {
  Metrics::{ font_size, line_height: font_size * line_height_scale }
}

///|
/// Scale font size and line height.
pub fn Metrics::scale(self : Metrics, scale : Float) -> Metrics {
  Metrics::{
    font_size: self.font_size * scale,
    line_height: self.line_height * scale,
  }
}
